version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      dev:
        ipv4_address: 10.10.10.253

  dns:
    image: jherrerotardon/dnsmasq:2.80
    container_name: dns
    volumes:
      - ./files/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports: 
      - 53:53
    networks:
      dev:
        ipv4_address: 10.10.10.2

  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
      - dns
    volumes:
      - ${PROJECTS_PATH}/php:/var/www:cached
      - ./files/nginx/config/conf.d:/etc/nginx/conf.d:cached
      - ./files/nginx/certs:/etc/ssl/certs:cached
      - ./logs/nginx:/var/log/nginx
    dns:
      - 10.10.10.2
    ports:
      - 80:80
      - 443:443
    networks:
      dev:
        ipv4_address: 10.10.10.3
        
  redis:
    container_name: redis
    image: redis
    depends_on: 
      - dns
    volumes: 
      - ./logs/redis:/var/log/redis
      - ./data/redis:/var/lib/redis
    dns:
      - 10.10.10.2
    ports:
    - 6376:6379
    networks:
      dev:
        ipv4_address: 10.10.10.20
  
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    depends_on: 
      - dns
    volumes:
      - ./logs/mongodb:/var/log/mongodb
      - ./data/mongodb:/data/db
    dns:
      - 10.10.10.2
    ports:
      - 27017:27017
    networks:
      dev:
        ipv4_address: 10.10.10.21

#  mariadb:
#    image: mariadb:10
#    container_name: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: development
#    depends_on:
#      - dns
#    volumes:
#      - ./logs/mariadb:/var/log/mysql
#      - ./data/mariadb:/var/lib/mysql
#    dns:
#      - 10.10.10.2
#    ports:
#      - 3306:3306
#    networks:
#      dev:
#        ipv4_address: 10.10.10.22

  php:
    image: jherrerotardon/php:7.4-fpm
    container_name: php
    depends_on: 
      - dns
    volumes:
      - ${PROJECTS_PATH}/php:/var/www:cached
      - ./files/php/config/:/usr/local/etc/:cached
      - ./logs/php:/var/log/php:cached
    dns:
      - 10.10.10.2
    ports: 
      - 9000:9000
    networks:
      dev:
        ipv4_address: 10.10.10.23

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    depends_on:
      - dns
    volumes: 
      - ./logs/rabbitmq:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq
    dns: 
      - 10.10.10.2
    ports:
      - 15672:15672
    networks:
      dev:
        ipv4_address: 10.10.10.24
  
  smtp:
    image: jherrerotardon/exim4
    container_name: smtp
    depends_on:
      - dns
    volumes: 
      - ./files/exim4/update-exim4.conf.conf:/etc/exim4/update-exim4.conf.conf:cached
    ports: 
      - 25:25
    dns: 
      - 10.10.10.2
    networks:
      dev:
        ipv4_address: 10.10.10.25

networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
